import {useEffect,useMemo,useState} from 'react'
import {FileUp} from 'lucide-react'
import {api,getError} from '../lib/api'
import {Card,ErrorBox,Loader,Modal,PageHeader,Status} from '../components/UI'

export default function Employees(){
  const [users,setUsers]=useState(null),[masters,setMasters]=useState([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[show,setShow]=useState(false),[importOpen,setImportOpen]=useState(false),[importFile,setImportFile]=useState(null),[busy,setBusy]=useState(false)
  const [form,setForm]=useState({name:'',email:'',password:'Admin@123',role:'employee',manager_id:'',designation_id:''})
  const load=()=>api.get('/admin/users').then(r=>setUsers(r.data)).catch(e=>setError(getError(e)))
  useEffect(()=>{load();api.get('/admin/masters').then(r=>setMasters(r.data)).catch(e=>setError(getError(e)))},[])
  const designations=useMemo(()=>masters.flatMap(d=>d.departments.flatMap(dep=>dep.designations.map(x=>({...x,label:`${d.name} / ${dep.name} / ${x.name}`})))),[masters])
  async function create(){try{setError('');await api.post('/admin/users',{...form,manager_id:form.manager_id?Number(form.manager_id):null,designation_id:form.designation_id?Number(form.designation_id):null});setShow(false);setForm({name:'',email:'',password:'Admin@123',role:'employee',manager_id:'',designation_id:''});load()}catch(e){setError(getError(e))}}
  async function toggle(u){try{await api.patch(`/admin/users/${u.id}`,{active:!u.active});load()}catch(e){setError(getError(e))}}
  async function importEmployees(){if(!importFile){setError('Choose an Excel or CSV file first.');return}setBusy(true);try{const fd=new FormData();fd.append('file',importFile);fd.append('preview','false');const {data}=await api.post('/admin/import-employees-excel',fd,{headers:{'Content-Type':'multipart/form-data'}});setMessage(`Imported ${data.created} employee(s); ${data.skipped} existing row(s) skipped.`);setImportOpen(false);setImportFile(null);load()}catch(e){setError(getError(e))}finally{setBusy(false)}}
  return <><PageHeader title="Employees" subtitle="Create employees and view their employee IDs." actions={<div className="row-actions"><button className="secondary" onClick={()=>setImportOpen(true)}><FileUp size={16}/>Import Employees</button><button className="primary" onClick={()=>setShow(!show)}>Add Employee</button></div>}/><ErrorBox error={error}/>{message?<div className="success-box">{message}</div>:null}{show?<Card><div className="form-grid"><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Temporary password<input value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="employee">Employee</option><option value="manager">Manager</option><option value="hr">HR</option><option value="superadmin">Super Admin</option></select></label><label>Designation<select value={form.designation_id} onChange={e=>setForm({...form,designation_id:e.target.value})}><option value="">None</option>{designations.map(x=><option value={x.id} key={x.id}>{x.label}</option>)}</select></label><label>Reporting manager<select value={form.manager_id} onChange={e=>setForm({...form,manager_id:e.target.value})}><option value="">None</option>{(users||[]).filter(u=>['manager','hr','superadmin'].includes(u.role)).map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select></label><button className="primary align-end" onClick={create}>Create user</button></div></Card>:null}{!users?<Loader/>:<Card><div className="table-wrap"><table><thead><tr><th>Employee ID</th><th>Name</th><th>Email</th><th>Role</th><th>Department</th><th>Designation</th><th>Reports to</th><th>Status</th><th></th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.employee_id||`EMP-${String(u.id).padStart(4,'0')}`}</strong></td><td>{u.name}</td><td>{u.email}</td><td>{u.role}</td><td>{u.department||'—'}</td><td>{u.designation||'—'}</td><td>{u.manager||'—'}</td><td><Status value={u.active?'active':'inactive'}/></td><td>{u.role!=='superadmin'?<button className="secondary small" onClick={()=>toggle(u)}>{u.active?'Deactivate':'Activate'}</button>:null}</td></tr>)}</tbody></table></div></Card>}{importOpen?<Modal title="Import employees" onClose={()=>setImportOpen(false)} actions={<><button className="secondary" onClick={()=>setImportOpen(false)}>Cancel</button><button className="primary" disabled={busy} onClick={importEmployees}>{busy?'Importing...':'Import file'}</button></>}><div className="form-grid"><label>Employee Excel / CSV<input type="file" accept=".xlsx,.xls,.csv" onChange={e=>setImportFile(e.target.files?.[0]||null)}/></label></div></Modal>:null}</>
}
